router.post('/create-task', auth, async (req, res) => {
  try {
    const { companyProfileId, title, description, targetPostingDate, submissionForReview } = req.body;

    // Validate company profile exists
    const companyProfile = await CompanyProfile.findById(companyProfileId);
    if (!companyProfile) {
      return res.status(404).json({ message: 'Company profile not found' });
    }

    // Create new task (taskId will be auto-generated by the pre-save hook)
    const task = new Task({
      companyProfileId,
      title,
      description,
      targetPostingDate,
      submissionForReview,
      currentStatus: 'Pending',
      createdBy: req.user._id
    });

    await task.save();
    res.status(201).json(task);
  } catch (error) {
    console.error('Error creating task:', error);
    res.status(500).json({ message: 'Error creating task', error: error.message });
  }
});